export default {
  tex1: "Faded Bar Graph",
  ex1: "The prices of dried onions in December 2015, 2016, 2017, 2018, 2019 were indicated by the Turkish Statistical Institute.",
  tex2: "Donut Graph",
  ex2: "The 2017 Turkish constitutional amendment referendum was a public vote held on 16 April 2017. Their results are indicated in the graph.",

  tex4: "Sigle Number",
  ex4: "Migros supermarket has made a 30% discount on all products.",
  tex5: "Stacked Column",
  ex5: "March 31, 2019 is the people's vote, which is called the local elections. Their results are indicated in the graph.",
  tex6: "Area Graph",
  ex6: "The prices of dried onions in December 2015, 2016, 2017, 2018, 2019 were indicated by the Turkish Statistical Institute.",
  tex7: "Bullet Graph",
  ex7: "This is a study conducted in Turkey. It was investigated which football team the public hired.",
  tex8: "Benchmark Line",
  ex8: "The value of the Turkish Lira against the dollar in the years 2017,2018,2019,2020,2021,2022 has been transferred to the chart.",
  tex9: "Bar Chart",
  ex9: "Population ratio by sex and age group (%), 2021",

  tex11: "Dot Plot",
  ex11: "It is the transfer of the height-weight ratio of the national athlete to the dot graph.",
  tex12: "Line Chart",
  ex12: "The proportion of individuals over the age of 25 and who have completed at least one level of education in the total population Dec 2008 and 2020",
  tex13: "Stacked Bar",
  ex13: "In August 2019, a Goose mountains survey was conducted by `MetroPOLL Research`. The question posed to the public has been “Can environmental pollution be tolerated for economic development”. The results were transferred to the chart.",
  tex14: "Small Multiples Graph",
  ex14: "January February March April 2022, the sales figures of Mercedes-Benz and Bmw brand cars in Turkey were announced. The results were transferred to the chart.",
  tex15: "Column Graph",
  ex15: "The prices of dried onions in December 2015, 2016, 2017, 2018, 2019 were indicated by the Turkish Statistical Institute.",

  tex17: "Pie Chart",
  ex17: "The value-added composition of the service sector (%, 2015)",
  tex18: "%100 Stacked Bar",
  ex18: "This is a study conducted in Turkey. It was investigated which football team the public hired.",

  tex21: "Scatter Plot",
  ex21: "There are twenty numbers at random. The positions of these numbers on the graph are determined by the x-axis and the y-axis. The numbers can be Decoded from 0 to 200.",
  qft1: "Graphic Suggestion Form",
  qft2: "Graphic Information Display",
  ab: "Which Chart Should I Used",
  modal: "Click Here For More Information About The Chart",
  tex22: "What Would You Like To Show?",
  tex23: "Is your data static or is it changing over time?",
  tex24: "How many variables do you have?",
  tex25: "How often will your data change?",
  tex26: "Is your data cyclical?",
  tex27:
    "Does your data consist of one or several items? Or does it consist of many elements?",
  tex28: "How many items do you have?",
  tex29: "What is the importance of the degree of difference of the data?",
  tex30: "Please select the chart type that suits your data",
  tex31: "Bubble Chart",
  ex31: "",
  tex32: "Stacked 100% Column Chart",
  ex32: "",
  sec1: "Karşılaştırma",
  sec2: "Relationship",
  sec3: "Composition",
  sec4: "Distribution",
  mod1: "A scatter plot (aka scatter plot, scatter plot) uses points to represent the values of two different numeric variables. The position of each point on the horizontal and vertical axes specifies the values for a single data point. Distribution graphs are used to observe the relationships Dec variables.",
  mod2: "A bubble chart is a data visualization that displays multiple circles (bubbles) on a two-dimensional chart. This is a generalization of the distribution graph by replacing points with bubbles. Most commonly, a bubble graph shows the values of three numerical variables, in which the data of each observation is indicated by a circle (bubble), while the horizontal and vertical positions of the bubble indicate the values of the other two variables.",
  mod3: "",
};
