export default {
  tex1: "Soluk Çubuk Grafik",
  ex1: "Türkiye İstatistik Kurumu tarafından 2015, 2016, 2017, 2018, 2019 yıllarının Aralık aylarında kuru soğan fiyatları belirtilmiştir.",
  tex2: "Çörek Grafik",
  ex2: "2017 Türkiye anayasa değişikliği referandumu, 16 Nisan 2017’de gerçekleşen halk oylamasıdır. Sonuçları grafikte belirtilmiştir.",
  tex3: "Simge Dizisi",
  ex3: "12/A sınıfı ders yoklamasıdır. Yedi kişi derse katılmıştır. Üç kişi ise derse katılmamıştır.",
  tex4: "Tek Sayı",
  ex4: "Migros adlı süpermarket tüm ürünlerde %30 indirim yapmıştır.",
  tex5: "Yığılmış Sütun",
  ex5: "31 Mart 2019 yerel seçimler olarak adlandırılan halk oylamasıdır. Sonuçları grafikte belirtilmiştir.",
  tex6: "Alan Grafiği",
  ex6: "Türkiye İstatistik Kurumu tarafından 2015, 2016, 2017, 2018, 2019 yıllarının Aralık aylarında kuru soğan fiyatları belirtilmiştir.",
  tex7: "Madde İşareti Grafiği",
  ex7: "Türkiye’de yapılmış araştırmadır. Halkın hangi futbol takımı tuttuğu araştırılmıştır.",
  tex8: "Kıyaslama Hattı",
  ex8: "Türk Lirası'nın 2017,2018,2019,2020,2021,2022 yıllarındaki dolar karşısındaki değeri grafiğe aktarılmıştır.",
  tex9: "Çubuk Grafik",
  ex9: "Cinsiyete ve yaş grubuna göre nüfus oranı (%), 2021",
  tex10: "Arka Arkaya Grafik",
  ex10: "Okul müdürü ve öğretmenlerin okul içindeki davranışlarının incelenmesi",
  tex11: "Nokta Çizimi",
  ex11: "Milli sporcunun boy-kilo oranının nokta grafiğine aktarılmasıdır.",
  tex12: "Çizgi Grafiği",
  ex12: "2008 – 2020 yılları arasında 25 ve daha yukarı yaşta olan ve en az bir eğitim düzeyini tamamlayan bireylerin toplan nüfus içindeki oranı ",
  tex13: "Yığılmış Çubuk",
  ex13: "Ağustos 2019'da `MetroPOLL Research` tarafından Kaz dağları araştırması yapılmıştır. Halka yöneltilen soru “Ekonomik kalkınma için çevre kirliliğine müsamaha gösterilebilir mi” olmuştur. Sonuçlar grafiğe aktarılmıştır.",
  tex14: "Küçük Katlar Grafiği",
  ex14: "2022 yılının Ocak,Şubat,Mart,Nisan aylarında Mercedes-Benz ve Bmw marka otomobil markalarının Türkiye'de satış sayıları belirtilmiştir. Sonuçlar grafiğe aktarılmıştır",
  tex15: "Sütun Grafiği",
  ex15: "Türkiye İstatistik Kurumu tarafından 2015, 2016, 2017, 2018, 2019 yıllarının Aralık aylarında kuru soğan fiyatları belirtilmiştir.",
  tex16: "Harita Grafiği",
  ex16: "Amerika haritası harita grafiğine aktarılmıştır",
  tex17: "Pasta Grafiği",
  ex17: "Hizmetler sektörünün Katma – Değer Kompozisyonu (%, 2015) ",
  tex18: "%100 Yığılmış Çubuk",
  ex18: "Türkiye’de yapılmış araştırmadır. Halkın hangi futbol takımı tuttuğu araştırılmıştır.",
  tex19: "Ağaç Haritası",
  ex19: "Eksen, etkinlikler, efsane, kontroller, veri ve operatör başlıklarının ağaç haritasına aktarılma çalışmasıdır.",
  tex20: "Diyagram",
  ex20: "Referans, Fark, Sensör, Girdiler, Sistem ve Çıktılardan diagram şeması çalışmasıdır.",
  tex21: "Dağılım Grafiği",
  ex21: "2.	Rastgele 20 sayı vardır. Bu sayıların grafik üzerindeki konumları x ekseni ve y eksenine göre belirlenmektedir. Sayılar 0 ile 200 arasında değer alabilmektedir.",
  ab: "Hangi Grafiği Kullanmalıyım",
  modal: "Grafik Hakkında Daha Fazla Bilgi İçin Tıklayınız",
  qft1: "Grafik Öneri Formu",
  qft2: "Grafik Bilgi Ekranı",
  tex22: "Ne Göstermek İstiyorsunuz?",
  tex23: "Verileriniz statik mi yoksa zaman içinde mi değişiyor?",
  tex24: "Kaç değişkeniniz var ?",
  tex25: "Verileriniz ne sıklıkla değişecek",
  tex26: "Verileriniz döngüsel mi?",
  tex27:
    "Verileriniz bir veya birkaç öğeden oluşuyor mu? Yoksa birçok unsurdan mı oluşuyor?",
  tex28: "Kaç öğeniz var?",
  tex29: "Verilerin farklılık derecesinin önemi nedir?",
  tex30: "Lütfen verilerinize uygun grafik türünü seçiniz",
  tex31: "Kabarcık Grafiği",
  ex31: "",
  tex32: "",
  ex32: "",
  sec1: "Karşılaştırma",
  sec2: "İlişki",
  sec3: "Bileşim",
  sec4: "Dağılım",
  mod1: "Bir dağılım grafiği (aka dağılım grafiği, dağılım grafiği), iki farklı sayısal değişkenin değerlerini temsil etmek için noktaları kullanır. Yatay ve dikey eksendeki her noktanın konumu, tek bir veri noktası için değerleri belirtir. Değişkenler arasındaki ilişkileri gözlemlemek için dağılım grafikleri kullanılır",
  mod2: "Kabarcık grafiği, iki boyutlu bir grafikte birden çok daire (kabarcık) görüntüleyen bir veri görselleştirmesidir. Bu, noktaları kabarcıklarla değiştirerek dağılım grafiğinin genelleştirilmesidir. En yaygın olarak, bir kabarcık grafiği, her gözlemin verilerinin bir daire (kabarcık) ile gösterildiği üç sayısal değişkenin değerlerini gösterirken, balonun yatay ve dikey konumları diğer iki değişkenin değerlerini gösterir.",
  mod3: "",
};
