export default {
  tex1: "Soluk Çubuk Grafik",
  ex1: "Türkiye İstatistik Kurumu tarafından 2015, 2016, 2017, 2018, 2019 yıllarının Aralık aylarında kuru soğan fiyatları belirtilmiştir.",
  tex2: "Çörek Grafik",
  ex2: "2017 Türkiye anayasa değişikliği referandumu, 16 Nisan 2017’de gerçekleşen halk oylamasıdır. Sonuçları grafikte belirtilmiştir.",
  tex3: "Simge Dizisi",
  ex3: "12/A sınıfı ders yoklamasıdır. Yedi kişi derse katılmıştır. Üç kişi ise derse katılmamıştır.",
  tex4: "Tek Sayı",
  ex4: "Migros adlı süpermarket tüm ürünlerde %30 indirim yapmıştır.",
  tex5: "Yığılmış Sütun",
  ex5: "31 Mart 2019 yerel seçimler olarak adlandırılan halk oylamasıdır. Sonuçları grafikte belirtilmiştir.",
  tex6: "Alan Grafiği",
  ex6: "Türkiye İstatistik Kurumu tarafından 2015, 2016, 2017, 2018, 2019 yıllarının Aralık aylarında kuru soğan fiyatları belirtilmiştir.",
  tex7: "Madde İşareti Grafiği",
  ex7: "Türkiye’de yapılmış araştırmadır. Halkın hangi futbol takımı tuttuğu araştırılmıştır.",
  tex8: "Kıyaslama Hattı",
  ex8: "Türk Lirası'nın 2017,2018,2019,2020,2021,2022 yıllarındaki dolar karşısındaki değeri grafiğe aktarılmıştır.",
  tex10: "Arka Arkaya Grafik",
  ex10: "Okul müdürü ve öğretmenlerin okul içindeki davranışlarının incelenmesi",
  tex11: "Nokta Çizimi",
  ex11: "Milli sporcunun boy-kilo oranının nokta grafiğine aktarılmasıdır.",
  tex12: "Çizgi Grafiği",
  ex12: "2008 – 2020 yılları arasında 25 ve daha yukarı yaşta olan ve en az bir eğitim düzeyini tamamlayan bireylerin toplan nüfus içindeki oranı ",
  tex13: "Yığılmış Çubuk",
  ex13: "Ağustos 2019'da `MetroPOLL Research` tarafından Kaz dağları araştırması yapılmıştır. Halka yöneltilen soru “Ekonomik kalkınma için çevre kirliliğine müsamaha gösterilebilir mi” olmuştur. Sonuçlar grafiğe aktarılmıştır.",
  tex14: "Küçük Katlar Grafiği",
  ex14: "2022 yılının Ocak,Şubat,Mart,Nisan aylarında Mercedes-Benz ve Bmw marka otomobil markalarının Türkiye'de satış sayıları belirtilmiştir. Sonuçlar grafiğe aktarılmıştır",
  tex15: "Sütun Grafiği",
  ex15: "Türkiye İstatistik Kurumu tarafından 2015, 2016, 2017, 2018, 2019 yıllarının Aralık aylarında kuru soğan fiyatları belirtilmiştir.",
  tex16: "Harita Grafiği",
  ex16: "Amerika haritası harita grafiğine aktarılmıştır",

  tex18: "%100 Yığılmış Çubuk",
  ex18: "Türkiye’de yapılmış araştırmadır. Halkın hangi futbol takımı tuttuğu araştırılmıştır.",
  tex19: "Ağaç Haritası",
  ex19: "Eksen, etkinlikler, efsane, kontroller, veri ve operatör başlıklarının ağaç haritasına aktarılma çalışmasıdır.",
  tex20: "Diyagram",
  ex20: "Referans, Fark, Sensör, Girdiler, Sistem ve Çıktılardan diagram şeması çalışmasıdır.",
  tex21: "Dağılım Grafiği",
  ex21: "Rastgele 20 sayı vardır. Bu sayıların grafik üzerindeki konumları x ekseni ve y eksenine göre belirlenmektedir. Sayılar 0 ile 200 arasında değer alabilmektedir.",
  ab: "Hangi Grafiği Kullanmalıyım",
  modal: "Grafik Hakkında Daha Fazla Bilgi İçin Tıklayınız",
  qft1: "Grafik Öneri Formu",
  qft2: "Grafik Bilgi Ekranı",
  tex22: "Ne Göstermek İstiyorsunuz?",
  tex23: "Verileriniz statik mi yoksa zaman içinde mi değişiyor?",
  tex24: "Kaç değişkeniniz var ?",
  tex25: "Verileriniz ne sıklıkla değişecek",
  tex26: "Verileriniz döngüsel mi?",
  tex27:
    "Verileriniz bir veya birkaç öğeden oluşuyor mu? Yoksa birçok unsurdan mı oluşuyor?",
  tex28: "Kaç öğeniz var?",
  tex29: "Verilerin farklılık derecesinin önemi nedir?",
  tex30: "Lütfen verilerinize uygun grafik türünü seçiniz",
  tex31: "Kabarcık Grafiği",
  ex31: "İki veri kümesi vardır. X ve Y eksenlerindeki değerler verilen değerleri alır. Örnekte, her kabarcık bir veri kümesini temsil eder. Kabarcıklar kapsama alanındaki üçüncü değişkeni temsil eder. Bu, zaman bilgisini gösterir.",
  tex32: "%100 Yığılmış Sütun Grafiği",
  ex32: "2022 yılının Ocak,Şubat,Mart,Nisan aylarında Mercedes-Benz ve Bmw marka otomobil markalarının Türkiye'de satış sayıları belirtilmiştir. Sonuçlar grafiğe aktarılmıştır",
  tex33: "Yığılmış Sütun Grafiği",
  ex33: "31 Mart 2019 yerel seçimler olarak adlandırılan halk oylamasıdır. Sonuçları grafikte belirtilmiştir. Yığılmış sütun grafiği dikey veya yatay olabilir. Her sütun bir veriyi temsil eder ve bir değer verilir. Sütunlara değerleri verildikten sonra karşılaştırma yapılabilir.",
  tex34: "%100 Yığılmış Alan Grafiği",
  ex34: "Üç veri kümesiyle oluşturulmuş bir alan grafiğidir. Verilerin zaman içindeki dalgalanmaları belirtilir.  Verilerin değerleri Kartezyen koordinat sistemine göre verilmiştir. Her veri kümesine farklı bir renk verilir ve karışıklıktan kaçınılır.",
  tex35: "Yığılmış Alan Grafiği",
  ex35: "2021 yılı, döviz kurlarının alan çizelgesine aktarılmasıdır. Bir alan grafiği için iki veri kümesi vardır. Bunlar euro ve dolar verileri. 'Uv' ve 'pv' değerlerini aldıktan sonra grafik oluşturulur.",
  tex36: "Pasta Grafiği",
  ex36: "Hizmetler sektörünün Katma – Değer Kompozisyonu (%, 2015). Dilimlerin toplam değerleri 100'e eşittir. Veriler değerlere göre grafiklendirilir. Kategorileri anlamak için renklendirme yapılır.",
  tex37: "Şelale Grafiği",
  ex37: "1990 ile 2017 yılları arasındaki karbon dengesi verilerinin şelale grafiğine aktarılmasıdır. İlk önce başlangıç değeri verilir. Daha sonra pozitif ve negatif değerler eklenir ve bir grafik oluşturulur.",
  tex38: "Alt Bileşenlerle Oluşturulmuş %100 Yığılmış Sütun Grafiği",
  ex38: "Üç sütundan oluşan bir grafik örneği. Alt bileşenler değişken olarak belirtilir. Değişken bilgisi eklenerek sütunlar ayrıştırılır ve grafikler arasında bir ilişki kurulur.",
  tex39: "Sütun Histogram",
  ex39: "Atom altı parçacıkların yüklerinin belirtildiği bir histogram grafiğidir. Veriler sütunlara eklenir ve renklendirilir. Ardından histogram grafiği oluşturulur.",
  tex40: "Çizgi Histogram",
  ex40: "Histogram, bir grup veri noktasını kullanıcı tarafından belirtilen aralıkta düzenleyen grafiksel bir gösterimdir. Bir çubuk grafiğe benzer şekilde, bir histogram birçok veri noktası alarak ve bunları mantıksal Aralık veya kutulara gruplayarak bir veri serisini kolayca yorumlanabilir bir görüntüye yoğunlaştırır.",
  tex41: "3D Alan Grafiği",
  ex41: "3B alan grafiği, veriler arasında daha verimli karşılaştırma sağlar. Veriler eklenip uygun renkler verilerek bir grafik oluşturulur. Örnekte, düşük değerlere mavi renk tonu ve yüksek değerlere kırmızı renk tonu verilmiştir.",
  tex42: "Tek Çubuk Grafik",
  ex42: "Türkiye İstatistik Kurumu tarafından 2015, 2016, 2017, 2018, 2019 yıllarının Aralık aylarında kuru soğan fiyatları belirtilmiştir.",
  tex43: "Değişken Genişlikli Sütun Grafiği",
  ex43: "Geleneksel çubuk grafiklerden farkı, sütunların eşit genişlikte olmamasıdır. Örnekte, sütunların genişliği değişkenlerin yüzdelerine göre belirlenir. Sütunların verileri ve renklendirmesi yapıldıktan sonra grafik oluşturulur.",
  tex44: "Çoklu Çubuk Grafikler",
  ex44: "Birden çok çubuk grafikle oluşturulmuş bir çalışmadır. Grafikler tek bir ekranda birleştirilir. Görselleştirme, kategorilerden ve çubuk grafiklerden veri eklenerek tamamlanır. Aynı konudaki çubuk grafikler örnekte yer almaktadır. Farklı bir konuda çubuk grafiğiniz olduğunda hedefe ulaşılmaktadır.",
  tex45: "Gömülü Grafiklere Sahip Tablo",
  ex45: "Tabloda birden fazla grafik bulunmaktadır.Farklı grafikleri tek bir ekranda görmek hedeflenmektedir. Örnekte, bir çubuk grafik, bir sütun grafiği ve farklı genişlikteki bir sütun grafiği tabloya dahil edilmiştir.",
  tex46: "Döngüsel Veriler",
  ex46: "Döngüsel verilerin görüntülenmesi amacıyla tasarlanan grafiktir. Örnekte, döngüsel bir veri grafiği verilmiştir. Veri ve kategoriler eklenerek bir grafik oluşturulur.",
  tex47: "Döngüsel Olmayan Veriler",
  ex47: "Döngüsel olmayan verilerin görüntülenmesi amacıyla tasarlanan grafiktir. Örnekte, döngüsel olmayan bir veri grafiği verilmiştir. Veri ve kategoriler eklenerek bir grafik oluşturulur. (Cinsiyete ve yaş grubuna göre nüfus oranı (%), 2021) ",
  tex48: "Sütun Grafik",
  ex48: "Nüfusun cinsiyet ve yaş grubuna göre oranı (%), 2021. Erkek ve kadın nüfusun yaş gruplarına göre yoğunluk oranları grafiğe yansıtılmıştır.",
  tex49: "Çizgi Grafik",
  ex49: "2008 – 2020 yılları arasında 25 ve daha yukarı yaşta olan ve en az bir eğitim düzeyini tamamlayan bireylerin toplan nüfus içindeki oranı. Erkek ve kadınlardan oluşan iki veri kümesi vardır. Yıllara göre oranlar ilgili veri kümesine eklenir ve bir grafik oluşturulur.",
  sec1: "Karşılaştırma",
  sec2: "İlişki",
  sec3: "Bileşim",
  sec4: "Dağılım",
  sec5: "Temizle",
  sec6: "Sabit",
  sec7: "Zamanla Değişim",
  sec8: "Birçok Dönem",
  sec9: "Birkaç Dönem",
  sec10: "Evet",
  sec11: "Hayır",
  sec12: "Bir veya Birkaç Öğe",
  sec13: "Birçok Öğe",
  mod1: "Bir dağılım grafiği (aka dağılım grafiği, dağılım grafiği), iki farklı sayısal değişkenin değerlerini temsil etmek için noktaları kullanır. Yatay ve dikey eksendeki her noktanın konumu, tek bir veri noktası için değerleri belirtir. Değişkenler arasındaki ilişkileri gözlemlemek için dağılım grafikleri kullanılır",
  mod2: "Kabarcık grafiği, iki boyutlu bir grafikte birden çok daire (kabarcık) görüntüleyen bir veri görselleştirmesidir. Bu, noktaları kabarcıklarla değiştirerek dağılım grafiğinin genelleştirilmesidir. En yaygın olarak, bir kabarcık grafiği, her gözlemin verilerinin bir daire (kabarcık) ile gösterildiği üç sayısal değişkenin değerlerini gösterirken, balonun yatay ve dikey konumları diğer iki değişkenin değerlerini gösterir.",
  mod3: "",
};
