export default {
  tex1: "Soluk Çubuk Grafik",
  ex1: "Türkiye İstatistik Kurumu tarafından 2015, 2016, 2017, 2018, 2019 yıllarının Aralık aylarında kuru soğan fiyatları belirtilmiştir.",
  tex2: "Çörek Grafik",
  ex2: "2017 Türkiye anayasa değişikliği referandumu, 16 Nisan 2017’de gerçekleşen halk oylamasıdır. Sonuçları grafikte belirtilmiştir.",
  tex3: "Simge Dizisi",
  ex3: "12/A sınıfı ders yoklamasıdır. Yedi kişi derse katılmıştır. Üç kişi ise derse katılmamıştır.",
  tex4: "Tek Sayı",
  ex4: "Migros adlı süpermarket tüm ürünlerde %30 indirim yapmıştır.",
  tex5: "Yığılmış Sütun",
  ex5: "31 Mart 2019 yerel seçimler olarak adlandırılan halk oylamasıdır. Sonuçları grafikte belirtilmiştir.",
  tex6: "Alan Grafiği",
  ex6: "Türkiye İstatistik Kurumu tarafından 2015, 2016, 2017, 2018, 2019 yıllarının Aralık aylarında kuru soğan fiyatları belirtilmiştir.",
  tex7: "Madde İşareti Grafiği",
  ex7: "Türkiye’de yapılmış araştırmadır. Halkın hangi futbol takımı tuttuğu araştırılmıştır.",
  tex8: "Kıyaslama Hattı",
  ex8: "Türk Lirası'nın 2017,2018,2019,2020,2021,2022 yıllarındaki dolar karşısındaki değeri grafiğe aktarılmıştır.",
  tex10: "Arka Arkaya Grafik",
  ex10: "Okul müdürü ve öğretmenlerin okul içindeki davranışlarının incelenmesi",
  tex11: "Nokta Çizimi",
  ex11: "Milli sporcunun boy-kilo oranının nokta grafiğine aktarılmasıdır.",
  tex12: "Çizgi Grafiği",
  ex12: "2008 – 2020 yılları arasında 25 ve daha yukarı yaşta olan ve en az bir eğitim düzeyini tamamlayan bireylerin toplan nüfus içindeki oranı ",
  tex13: "Yığılmış Çubuk",
  ex13: "Ağustos 2019'da `MetroPOLL Research` tarafından Kaz dağları araştırması yapılmıştır. Halka yöneltilen soru “Ekonomik kalkınma için çevre kirliliğine müsamaha gösterilebilir mi” olmuştur. Sonuçlar grafiğe aktarılmıştır.",
  tex14: "Küçük Katlar Grafiği",
  ex14: "2022 yılının Ocak,Şubat,Mart,Nisan aylarında Mercedes-Benz ve Bmw marka otomobil markalarının Türkiye'de satış sayıları belirtilmiştir. Sonuçlar grafiğe aktarılmıştır",
  tex15: "Sütun Grafiği",
  ex15: "Türkiye İstatistik Kurumu tarafından 2015, 2016, 2017, 2018, 2019 yıllarının Aralık aylarında kuru soğan fiyatları belirtilmiştir.",
  tex16: "Harita Grafiği",
  ex16: "Amerika haritası harita grafiğine aktarılmıştır",

  tex18: "%100 Yığılmış Çubuk",
  ex18: "Türkiye’de yapılmış araştırmadır. Halkın hangi futbol takımı tuttuğu araştırılmıştır.",
  tex19: "Ağaç Haritası",
  ex19: "Eksen, etkinlikler, efsane, kontroller, veri ve operatör başlıklarının ağaç haritasına aktarılma çalışmasıdır.",
  tex20: "Diyagram",
  ex20: "Referans, Fark, Sensör, Girdiler, Sistem ve Çıktılardan diagram şeması çalışmasıdır.",
  tex21: "Dağılım Grafiği",
  ex21: "Rastgele 20 sayı vardır. Bu sayıların grafik üzerindeki konumları x ekseni ve y eksenine göre belirlenmektedir. Sayılar 0 ile 200 arasında değer alabilmektedir.",
  ab: "Hangi Grafiği Kullanmalıyım",
  modal: "Grafik Hakkında Daha Fazla Bilgi İçin Tıklayınız",
  qft1: "Grafik Öneri Formu",
  qft2: "Grafik Bilgi Ekranı",
  tex22: "Ne Göstermek İstiyorsunuz?",
  tex23: "Verileriniz statik mi yoksa zaman içinde mi değişiyor?",
  tex24: "Kaç değişkeniniz var ?",
  tex25: "Verileriniz ne sıklıkla değişecek",
  tex26: "Verileriniz döngüsel mi?",
  tex27:
    "Verileriniz bir veya birkaç öğeden oluşuyor mu? Yoksa birçok unsurdan mı oluşuyor?",
  tex28: "Kaç öğeniz var?",
  tex29: "Verilerin farklılık derecesinin önemi nedir?",
  tex30: "Lütfen verilerinize uygun grafik türünü seçiniz",
  tex31: "Kabarcık Grafiği",
  ex31: "İki veri kümesi vardır. X ve Y eksenlerindeki değerler verilen değerleri alır. Örnekte, her kabarcık bir veri kümesini temsil eder. Kabarcıklar kapsama alanındaki üçüncü değişkeni temsil eder. Bu, zaman bilgisini gösterir.",
  tex32: "%100 Yığılmış Sütun Grafiği",
  ex32: "2022 yılının Ocak,Şubat,Mart,Nisan aylarında Mercedes-Benz ve Bmw marka otomobil markalarının Türkiye'de satış sayıları belirtilmiştir. Sonuçlar grafiğe aktarılmıştır",
  tex33: "Yığılmış Sütun Grafiği",
  ex33: "31 Mart 2019 yerel seçimler olarak adlandırılan halk oylamasıdır. Sonuçları grafikte belirtilmiştir. Yığılmış sütun grafiği dikey veya yatay olabilir. Her sütun bir veriyi temsil eder ve bir değer verilir. Sütunlara değerleri verildikten sonra karşılaştırma yapılabilir.",
  tex34: "%100 Yığılmış Alan Grafiği",
  ex34: "Üç veri kümesiyle oluşturulmuş bir alan grafiğidir. Verilerin zaman içindeki dalgalanmaları belirtilir.  Verilerin değerleri Kartezyen koordinat sistemine göre verilmiştir. Her veri kümesine farklı bir renk verilir ve karışıklıktan kaçınılır.",
  tex35: "Yığılmış Alan Grafiği",
  ex35: "2021 yılı, döviz kurlarının alan çizelgesine aktarılmasıdır. Bir alan grafiği için iki veri kümesi vardır. Bunlar euro ve dolar verileri. 'Uv' ve 'pv' değerlerini aldıktan sonra grafik oluşturulur.",
  tex36: "Pasta Grafiği",
  ex36: "Hizmetler sektörünün Katma – Değer Kompozisyonu (%, 2015). Dilimlerin toplam değerleri 100'e eşittir. Veriler değerlere göre grafiklendirilir. Kategorileri anlamak için renklendirme yapılır.",
  tex37: "Şelale Grafiği",
  ex37: "1990 ile 2017 yılları arasındaki karbon dengesi verilerinin şelale grafiğine aktarılmasıdır. İlk önce başlangıç değeri verilir. Daha sonra pozitif ve negatif değerler eklenir ve bir grafik oluşturulur.",
  tex38: "Alt Bileşenlerle Oluşturulmuş %100 Yığılmış Sütun Grafiği",
  ex38: "Üç sütundan oluşan bir grafik örneği. Alt bileşenler değişken olarak belirtilir. Değişken bilgisi eklenerek sütunlar ayrıştırılır ve grafikler arasında bir ilişki kurulur.",
  tex39: "Sütun Histogram",
  ex39: "Atom altı parçacıkların yüklerinin belirtildiği bir histogram grafiğidir. Veriler sütunlara eklenir ve renklendirilir. Ardından histogram grafiği oluşturulur.",
  tex40: "Çizgi Histogram",
  ex40: "Dolar kurunun 2017, 2018, 2019, 2020, 2021 ve 2022 yıllarındaki Türk Lirası karşısındaki değeri çizgi histogram grafiğine aktarılmıştır. Kategoriler belirlenir, veriler eklenir.  Bir sütunun en üst kısımlarından diğerine bir çizgi çizilir ve bir grafik oluşturulur.",
  tex41: "3D Alan Grafiği",
  ex41: "3B alan grafiği, veriler arasında daha verimli karşılaştırma sağlar. Veriler eklenip uygun renkler verilerek bir grafik oluşturulur. Örnekte, düşük değerlere mavi renk tonu ve yüksek değerlere kırmızı renk tonu verilmiştir.",
  tex42: "Tek Çubuk Grafik",
  ex42: "Türkiye İstatistik Kurumu tarafından 2015, 2016, 2017, 2018, 2019 yıllarının Aralık aylarında kuru soğan fiyatları belirtilmiştir.",
  tex43: "Değişken Genişlikli Sütun Grafiği",
  ex43: "Geleneksel çubuk grafiklerden farkı, sütunların eşit genişlikte olmamasıdır. Örnekte, sütunların genişliği değişkenlerin yüzdelerine göre belirlenir. Sütunların verileri ve renklendirmesi yapıldıktan sonra grafik oluşturulur.",
  tex44: "Çoklu Çubuk Grafikler",
  ex44: "Birden çok çubuk grafikle oluşturulmuş bir çalışmadır. Grafikler tek bir ekranda birleştirilir. Görselleştirme, kategorilerden ve çubuk grafiklerden veri eklenerek tamamlanır. Aynı konudaki çubuk grafikler örnekte yer almaktadır. Farklı bir konuda çubuk grafiğiniz olduğunda hedefe ulaşılmaktadır.",
  tex45: "Gömülü Grafiklere Sahip Tablo",
  ex45: "Tabloda birden fazla grafik bulunmaktadır.Farklı grafikleri tek bir ekranda görmek hedeflenmektedir. Örnekte, bir çubuk grafik, bir sütun grafiği ve farklı genişlikteki bir sütun grafiği tabloya dahil edilmiştir.",
  tex46: "Döngüsel Veriler",
  ex46: "Döngüsel verilerin görüntülenmesi amacıyla tasarlanan grafiktir. Örnekte, döngüsel bir veri grafiği verilmiştir. Veri ve kategoriler eklenerek bir grafik oluşturulur.",
  tex47: "Döngüsel Olmayan Veriler",
  ex47: "Döngüsel olmayan verilerin görüntülenmesi amacıyla tasarlanan grafiktir. Örnekte, döngüsel olmayan bir veri grafiği verilmiştir. Veri ve kategoriler eklenerek bir grafik oluşturulur. (Cinsiyete ve yaş grubuna göre nüfus oranı (%), 2021) ",
  tex48: "Sütun Grafik",
  ex48: "Nüfusun cinsiyet ve yaş grubuna göre oranı (%), 2021. Erkek ve kadın nüfusun yaş gruplarına göre yoğunluk oranları grafiğe yansıtılmıştır.",
  tex49: "Çizgi Grafik",
  ex49: "2008 – 2020 yılları arasında 25 ve daha yukarı yaşta olan ve en az bir eğitim düzeyini tamamlayan bireylerin toplan nüfus içindeki oranı. Erkek ve kadınlardan oluşan iki veri kümesi vardır. Yıllara göre oranlar ilgili veri kümesine eklenir ve bir grafik oluşturulur.",
  sec1: "Karşılaştırma",
  sec2: "İlişki",
  sec3: "Bileşim",
  sec4: "Dağılım",
  sec5: "Temizle",
  sec6: "Sabit",
  sec7: "Zamanla Değişim",
  sec8: "Birçok Dönem",
  sec9: "Birkaç Dönem",
  sec10: "Evet",
  sec11: "Hayır",
  sec12: "Bir veya Birkaç Öğe",
  sec13: "Birçok Öğe",
  sec14: "Birkaç Öğe",
  sec15: "Birkaç Dönem",
  sec16: "Birçok Dönem",
  sec17: "Göreceli Farklılıklardan Biri Önemlidir",
  sec18: "Göreceli ve Mutlak Farklılıklar Önemlidir",
  sec19: "Toplamın Basit Payı",
  sec20: "Toplamda Toplama veya Çıkarma",
  sec21: "Bileşenlerin Bileşeni",
  mod1: "Dağılım Grafiği, iki değişkenin değerlerini görüntülemek için kartezyen koordinatlar kullanılarak yerleştirilen bir noktalar topluluğu kullanır. Her eksende bir değişken görüntülenerek, iki değişken arasındaki ilişkinin veya korelasyonun mevcut olup olmadığını tespit edilebilir.",
  mod2: "Kabarcık Grafikleri, Dağılım Grafiği gibi bir kartezyen koordinat sistemi kullanarak sayısal bir sistem etrafında çalışırken, X ve Y eksenleri değişken değerler alır. Buna rağmen, bir Dağılım Grafiğinin aksine, her nokta bir katman veya kategori belirtmek için kullanılabilir. (Bir gösterge veya sıralama şeklinde). Çizilen her nokta kendi kapsama alanı içinde üçüncü bir değişkeni temsil eder. Değişkeni bir eksen üzerindeki veri değişkenleri akışında göstererek zamanlamayı gösterir. Renklendirme, kategorileri ayırmak veya Ekim veri değişkenlerini ayırt etmek için kullanılabilir.",
  mod3: "%100 yığılmış sütun grafiği, yığılmış sütunların toplamının (kümülatif) her zaman %100'e eşit olduğu, yığılmış sütunlarda birden çok veri serisinin göreli yüzdesini göstermesi amaçlanan bir Excel grafik türüdür. %100 yığılmış sütun grafiği, zaman içinde parçadan bütüne oranları gösterebilir, örneğin bölge başına üç aylık satışların oranı veya faize karşı anaparaya giden aylık ipotek ödemesinin oranı.",
  mod4: "Sütunları yan yana görüntüleyen Çoklu Çubuk Grafiği’nin aksine Yığılmış Çubuk Grafikleri, çoklu veri setinin sütunlarını birbiri üzerinden böler. Daha büyük bir kategorinin daha küçük kategorilere nasıl bölündüğünü ve her parçanın ilişkisinin toplam miktar üzerindeki oranını göstermek için kullanılırlar.",
  mod5: "% 100 Yığılmış Alan Grafiği, verilerin alan olarak çizildiği ve kümülatif alanın her zaman% 100'ü temsil edecek şekilde yığıldığı yerleşik bir Excel grafik türüdür. Yığılmış Alan grafikleri zaman içinde bir ilerleme ve kompozisyon gösterebilir ve% 100 Yığılmış Alan Grafiği, kümülatif toplam önemli olmadığında her bileşenin katkıda bulunduğu yüzdeyi göstermek içindir.",
  mod6: "İstiflenmiş / Yığılı Alan Grafikleri, önceki grafik dizisinin bıraktığı noktadan her noktaya başlamak üzere basit Alan Grafiklerinde olduğu gibi çalışır, tek farkı birden çok veri serisinin görselleştirilmesidir. Grafiğin tamamı gösterilen tüm verilerin toplamını temsil eder. İstiflenmiş/ yığılmış alan grafikleri de alanı tam sayıları iletmek için kullanır, bu nedenle negatif değerler için kullanılmazlar. Genel olarak, bir aralıkta değişen çoklu değişkenleri karşılaştırmak için kullanışlıdırlar.",
  mod7: "Sunumlar ve ofislerde yaygın olarak kullanılan Pasta Grafikler, bir daireyi orantılı bölümlere bölerek, kategoriler arasında oranlar ve yüzdeler göstermeye yardımcı olur. Her bir yay uzunluğu her bir kategorinin bir oranını temsil ederken, tam daire % 100'e eşit olan tüm verilerin toplamını temsil eder. Pasta grafikleri, okuyucunun verilerin orantılı dağılımı hakkında hızlı bir fikir vermek için idealdir.",
  mod8: "Şelale grafik, değer eklenip çıkarıldıkça değişen toplamı gösterir. Bir başlangıç değerinin (örneğin, net gelir) bir dizi pozitif ve negatif değerlerden nasıl etkilendiğini anlamak için kullanışlıdır. Sütunlar renk kodludur ve böylece pozitif negatif sayıları hızlı bir şekilde ayırt edebilirsiniz. İlk ve son değer sütunları çoğu zaman yatay eksen üzerinde başlarken,ara değerler kayan sütunlar olur. Bu 'görünüşü' nedeniyle, Şelale grafiklere köprü grafikler de denir.",
  mod9: "Verilerin devam eden veya belirli zaman aralığı dağılımını göstermek için bir 'Histogram' grafiği kullanılır. Histogramdaki her çubuk / Aralık, bölmedeki verilerin değerini gösterir. Tüm çubuklarının gösterdiği değerlerin toplamı, grafikte kullanılan verilerin sayısal değerine eşittir.Histogramlar değerlerin nerede yoğunlaştığını, maksimum ve minimum noktalarını, veriler arasındaki kopmalar ve olağandışı değerler olup olmadığı hakkında tahminde bulunulmasına yardımcı olur. Ayrıca “olasılık” dağılımı hakkında genel bir izlenim vermeleri bakımından yararlıdırlar. ",
  mod10:
    "3B alan grafiği, belirli bir süre içindeki değişiklik miktarını vurgular veya birden çok öğeyi karşılaştırır. 3B alan grafikleri, çizilen değerlerin toplamını görüntüleyerek parçaların bir bütünle ilişkisini de gösterir. Ekim alanı grafiği bir çizgi grafiği biçimidir, ancak x ekseni (yatay eksen) ile veri işaretleyicilerini birbirine bağlayan çizgi arasındaki boşluk Aralık ile doldurulur. Bu, farklı veri serilerinin kapsadığı noktaların nerede çakıştığını görmeyi kolaylaştırır.",
  mod11:
    "Basit bir çubuk grafik, uzamsal, nicel veya zamansal olarak sınıflandırılan yalnızca bir değişken içeren verileri temsil etmek için kullanılır. Basit bir çubuk grafikte, eşit genişlikte ancak değişken uzunlukta çubuklar yaparız, yani bir miktarın boyutu çubukların yüksekliği veya uzunluğu ile temsil edilir.",
  mod12:
    "Çubuk Mekko grafiği olarak da bilinen değişken genişlikli sütun grafiği, sütun genişliklerinin, toplam genişlik istenen grafik genişliğiyle eşleşecek ve sütunlar arasında boşluk kalmayacak şekilde ölçeklendirildiği bir çubuk grafiktir. Bu grafik, verilerdeki her kategori için iki farklı değişkenin değerlerini izlemek için kullanılabilir.",
  mod13:
    "Gruplanmış Çubuk Grafik veya Kümelenmiş Çubuk Grafiği olarak da bilinir. Çubuk grafiğin bu varyasyonu, iki veya daha fazla veri serisi yan yana çizilmekte ve kategoriler altında aynı eksende gruplandığında kullanılmaktadır. Çubuk grafikler gibi, her çubuğun uzunluğu kategoriler arasında ayrık, sayısal karşılaştırmalar yapmak için kullanılır. Her bir veri serisine, onları ayırt etmek için tek bir renk veya aynı renkteki değişen bir gölge atanır. Her bir sütun grubu birbirinden ayrı durur.",
  mod14:
    "Görselleştirme, aşağıdakileri yapmamızı sağlayan her türlü grafik temsilidir: Keşif , büyük miktarda veri aracılığıyla daha derin bir içgörü elde etmemize yardımcı olur. Keşif , büyük miktarda veri aracılığıyla daha derin bir içgörü elde etmemize yardımcı olur, Ortaya çıkarmak ayrıca ekstra görüş sağlar, Analiz desen bulmak için kullanılabilir, İletişim , görselleştirme daha iyi iletişim kurmamıza yardımcı olur.",
  mod15:
    "Örümcek Grafiği, Ağ Şeması, Kutup Şeması, Yıldız Çizimi olarak da bilinir. Radar grafiği, çoklu nicel değişkenleri karşılaştırmak için kullanılır. Hangi değişkenlerin benzer değerlere sahip olduğunu veya değişkenler arasındaki sapmaları göstermek için faydalıdır. Bununla birlikte, radar grafiği, bir veri seti içindeki değişkenlerin yüksek veya alçak değerlerini görmek ve bunların performanslarının karşılaştırılmasına da olanak tanır.",
  mod16:
    "Çizgi grafikler, devam eden veya belirli bir zaman aralığında “sayısal” değişiklikleri göstermek için kullanılır. Çizgi grafikler gruplandırıldığında, Aralık verileri arasındaki eğilimleri ve ilişkileri gösterirler. Bu grafikler aynı zamanda olayların nasıl geliştiği ve devam ettiği açısından “büyük resmi” anlamaya yardımcı olur. Bir çizgi grafiği oluşturmak için önce kartezyen koordinat sistemindeki veri noktalarını işaretlemek gerekir. Daha sonra 'x' ve 'y' ekseni arasındaki noktalar bir çizgi ile bağlanır Dec Tipik olarak, 'y' ekseni 'nicel'(sayısal) bir değere sahipken, 'x' ekseni bir kategori veya sıralama ölçeğine sahiptir. Negatif değerler 'x' ekseninin altında görüntülenebilir.",
  mod17:
    "Sütun grafiği, verileri bir dikdörtgenle temsil edilen kategorilerle (bazen dikey çubuk grafikler olarak adlandırılır) görüntüleme yöntemidir. Kolay karşılaştırma Dec öğeleri ve trend analizi bir dizi sağlar. Genel olarak, istatistikler ve rakamlar tablolarda veya yazılı olarak sunulduğunda anlaşılması zordur. Sütun grafikleri işleri kolay, hızlı ve anlaşılır hale getirir.",
  mod18: "Kaynak",
};
